sudo: true
language: python
matrix:
    include:
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=py27 RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=py27 RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=py27 RUN_INTEGRATION_TESTS=1
        - python: 3.3
          os: linux
          dist: precise
          env: TOXENV=py33 RUN_INTEGRATION_TESTS=0
        - python: 3.3
          os: linux
          dist: trusty
          env: TOXENV=py33 RUN_INTEGRATION_TESTS=0
        - python: 3.3
          os: linux
          dist: trusty
          env: TOXENV=py33 RUN_INTEGRATION_TESTS=1
        - python: 3.4
          os: linux
          dist: precise
          env: TOXENV=py34 RUN_INTEGRATION_TESTS=0
        - python: 3.4
          os: linux
          dist: trusty
          env: TOXENV=py34 RUN_INTEGRATION_TESTS=0
        - python: 3.5
          os: linux
          dist: precise
          env: TOXENV=py35 RUN_INTEGRATION_TESTS=0
        - python: 3.5
          os: linux
          dist: trusty
          env: TOXENV=py35 RUN_INTEGRATION_TESTS=0
        - python: 3.6
          os: linux
          dist: precise
          env: TOXENV=py36 RUN_INTEGRATION_TESTS=0
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=py36 RUN_INTEGRATION_TESTS=0
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=py36 RUN_INTEGRATION_TESTS=1
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=pep8 RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=pep8 RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: precise
          env: TOXENV=bandit RUN_INTEGRATION_TESTS=0
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=bandit RUN_INTEGRATION_TESTS=0
install:
  - pip install tox
  - pip install bandit
  - pip install codecov
  - python setup.py install
script:
  - ./.travis/run.sh
after_success:
  - codecov
